// This file contains all the constant related to the action of sagas

// eslint-disable-next-line import/prefer-default-export
export const ActionTypes = {
   SIGNUP : 'signup_create',
   OTP_VERIFY : 'otp_verify',
   LOGIN : 'login_create',
   SECURITY_QUESTION : 'security_question_create',
   GET_PROFILE : 'get_profile',
   LOGOUT:"logout",
   FORGOT_PASSWORD:'forgot_password',
 
 



    SET_INITIAL_POPUP : "SET_INITIAL_POPUP",
    GET_INITIAL_POPUP : "GET_INITIAL_POPUP",
    SAVE_INITIAL_POPUP : "SAVE_INITIAL_POPUP",
  

  
    GET_MAINTENANCE_ALERT :"GET_MAINTENANCE_ALERT",
    SET_MAINTENANCE_ALERT :"SET_MAINTENANCE_ALERT",
    REMOVE_MAINTENANCE_ALERT :"REMOVE_MAINTENANCE_ALERT",
  
  
    GET_INITIATE_LOGIN: 'GET_INITIATE_LOGIN',
    SET_INITIATE_LOGIN: 'SET_INITIATE_LOGIN',
    SET_LOCKED_ACCOUNT: 'SET_LOCKED_ACCOUNT',
  
    SET_ACTIVE_COUNTRY_CONFIG: 'SET_ACTIVE_COUNTRY_CONFIG',
    SAVE_ACTIVE_COUNTRY_CONFIG: 'SAVE_ACTIVE_COUNTRY_CONFIG',
  
    SAVE_COUNTRY_LIST :"SAVE_COUNTRY_LIST",
    SET_COUNTRY_LIST:"SET_COUNTRY_LIST",
  
    SET_QUICKPAY_CONFIG: 'SET_QUICKPAY_CONFIG',
    SAVE_QUICKPAY_CONFIG: 'SAVE_QUICKPAY_CONFIG',
  
  
    SET_IS_ERROR_BOUNDARY:'SET_IS_ERROR_BOUDNARY',
    SAVE_IS_ERROR_BOUNDARY:'SAVE_IS_ERROR_BOUNDARY',
  
    SET_SHOW_FALLBACK_UI:'SET_SHOW_FALLBACK_UI',
    SAVE_SHOW_FALLBACK_UI:'SAVE_SHOW_FALLBACK_UI',
  
    SAVE_IS_NEW_EVENT:'SAVE_IS_NEW_EVENT',
    SET_IS_NEW_EVENT:'SET_IS_NEW_EVENT',
    GET_IS_NEW_EVENT:'GET_IS_NEW_EVENT',
  
    GET_UNIFIED_PAYMENT_API_TOKEN: 'GET_UNIFIED_PAYMENT_API_TOKEN',
    SET_ACTIVE_LANGUAGE_COUNTRY: 'SET_ACTIVE_LANGUAGE_COUNTRY',
    SAVE_LANGUAGE_COUNTRY: 'SAVE_LANGUAGE_COUNTRY',
  
    GET_INITIATE_LOGOUT: 'GET_INITIATE_LOGOUT',
    ERROR_INITIATE_LOGOUT: 'ERROR_INITIATE_LOGOUT',
  
    SET_USER_DATA: 'SET_USER_DATA',
  
   
  
  
  };
  
  